### ISSUE TITLE
Support for audio tasks?

### ISSUE THREAD

**Issue by WillSike69** [akioweh/EducationPerfected#41]
Hey, this is mainly a suggestion/question, but when will support for audio tasks be released? 
Using NazierH's Traffic Interceptor (mitmproxy) it seems to be possible, but I do not have the time to code it in myself. 
https://github.com/NazierH/Education-Perfect-Answer-Interceptor

**Comment by akioweh** [comment]
Since these are all hobby-based projects, the amount of effort put into them aren't guaranteed. 
Last time I looked at adding support for audio tasks I did not find a fully viable method... (from what I can remember) because I did not find a way to check what question it is in the task page of an audio task. The question-answer pairs are sent before then entire task begins and differentiating the questions is the problem. At least, that where I think I got stuck. 
I don't have any experience with web client frameworks (EP uses Angular and some others) so I have no idea how the audio question is programmed.

**Comment by DanielWilliams78** [comment]
I've been trying to figure this problem out. But so far without result.

**Comment by NicholasBarrett98** [comment]
Since I have to write my dissertation, this is what I need. I think to apply dissertation proposal writing help and with a laptop it will be faster. And some part of the dissertation I will be able to write on my own.

**Comment by DamnUi** [comment]
Hi @WillSike69  @akioweh i recreated a program like this in python which gives about the same speed as v1 and have found a possible method to automate audio tasks but need a javascript dev, please get in contact with me through this or discord - nonja.
